config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad

  authenticate :admin_user do
    namespace :admin do
      namespace :metrics do
        resources :clients, only: [] do
          get 'not_bussiness', on: :collection
          get 'bussiness', on: :collection
          get 'last_n_days', on: :collection
        end

        resources :pros, only: [:index] do
          get 'set_master', on: :collection
        end

        resources :districts, only: [:index] do
          get 'set_city',          on: :collection
          get 'average_price',     on: :collection
          get 'orders_count_cat',  on: :collection
          get 'clients_by_gender', on: :collection
          get 'clients_by_age',    on: :collection
        end
      end
      namespace :panel do
        get '/', to: 'dashboards#index'
        post '/reassing_pro', to: 'dashboards#reassign_orders_pro'
        get '/get_pro_info', to: 'dashboards#get_info_pro'
        resources :companies
        resources :stations, only: [:index, :show, :new, :create, :edit, :update] do
          get :dashboard, on: :collection
        end
        resources :pros do
          post 'get_tips', on: :collection
          resource :payment,         only: [:show]
          resources :work_hours, only: [:create, :update]
          resources :stripe_account, only: [:new, :create, :edit, :update], controller: :pro_stripe_account
        end
        resources :admin_users
        resources :order_items, only: [:new, :create, :index, :show, :edit, :update] do
          post 'cancel'    , on: :collection
          post :change_time, on: :collection
        end
        resources :settings, except: [:destroy]
        resources :profile,  only: [:index]
        resources :clients do
          get 'upload_xls', on: :collection
          post 'import_xls', on: :collection
          resources :contract,      only: [:new, :create, :edit, :update]
        end
        resources :gift_cards, only: [:index, :show, :edit, :update]
        resources :email_texts
        resources :promo_codes, only: [:index, :show, :edit, :update, :new, :create]
        resources :faq_clients
        resources :faq_pros
        resources :demo_requests, only: [:index, :show]
        resources :services
        resources :categories do
          put 'sortable_update', on: :collection
        end
        resources :subcategories do
          put 'sortable_update', on: :collection
        end
        resources :tariff_plans
        resources :teams
        resources :countries
        resources :cities
        resources :districts
        resources :banners
        resources :offices
        resources :call_mes, only: [:index, :show]
        resources :devices, only: [:index, :show, :destroy]
        resources :client_feedbacks, only: [:index, :show]
        resources :pro_feedbacks, only: [:index, :show]
        

        resources :contract_dates, only: [:new, :create]
        resources :join_pros, only: [:index, :show]
        resources :sms_histories
        resources :term_conditions, only: [:index, :edit, :update]
        resources :tariff_plans
        resources :transports
        resources :referals, only: [:index, :show]
        resources :station_services, only: [:edit, :update, :show]

        get :search_clients,        to: 'queries#search_clients'
        get :check_cards,           to: 'queries#check_cards'
        post :add_cards,            to: 'queries#add_cards'
      end
    end
    resources :metrics,       only: [:index],     to: 'metrics#index'
    resource  :admin_images,  only: [:destroy]
    get :percentage_orders_and_categories,        to: 'charts#percentage_orders_and_categories'
    get :average_price_category,                  to: 'charts#average_price_category'
    get :last_n_days,                             to: 'charts#last_n_days'
    get :dayly_rate_last_n_days,                  to: 'charts#dayly_rate_last_n_days'
    get :created_order_by_platform,               to: 'charts#created_order_by_platform'
    get :clients_by_type,                         to: 'charts#clients_by_type'
    get :orders_by_clients,                       to: 'charts#orders_by_clients'
    get :order_period_values,                     to: 'charts#order_period_values'
    get :orders_frequency,                        to: 'charts#orders_frequency'
    get :clients_retention,                       to: 'charts#clients_retention'
    get :small_large_cars_percent,                to: 'charts#small_large_cars_percent'
    get :profit_on_services,                      to: 'charts#profit_on_services'
    get :most_ordered_service,                    to: 'charts#most_ordered_service'
    get :pros_count,                              to: 'charts#pros_count'
    get :canceled_orders,                         to: 'charts#canceled_orders'
    get :completed_orders,                        to: 'charts#completed_orders'
    get :accepted_orders,                         to: 'charts#accepted_orders'
    get :masters_orders_by_client_type,           to: 'charts#masters_orders_by_client_type'
    get :masters_orders_by_category,              to: 'charts#masters_orders_by_category'
    get :orders_by_district,                      to: 'charts#orders_by_district'
    get :master_average_time_orders,              to: 'charts#master_average_time_orders'
    get :clients_by_gender,                       to: 'charts#clients_by_gender'
    get :clients_by_age,                          to: 'charts#clients_by_age'
    get :orders_by_company_platforms,             to: 'charts#orders_by_company_platforms'
    get :cars_count_by_type,                      to: 'charts#cars_count_by_type'
    get :pros_by_type,                            to: 'charts#pros_by_type'
    get :turnover_by_platfroms,                   to: 'charts#turnover_by_platfroms'
    get :clients_count_by_segment,                to: 'charts#clients_count_by_segment'
    mount Sidekiq::Web, at: '/sidekiq'
  end

  root 'welcome#index'

  namespace :api, defaults: { format: :json } do

    namespace :v2 do
      namespace :auth do
        post 'provider/facebook',    to: 'socials#facebook'
        post 'provider/google',      to: 'socials#google'
        post 'generate',             to: 'verifications#generate'
        post 'verify_code',          to: 'verifications#verify_code'

        resources :passwordsms, only: [:create]
        scope module: 'passwordsms' do
          resources :send,   only: [:create], path: '/passwordsms/send'
          resources :verify, only: [:create], path: '/passwordsms/verify'
          # TODO заменить на reource. Следовательно в контроллерах убрать
          # s
        end
      end
      namespace :users do
        resources :client, only: [:index, :show]
        resources :masters, param: :master_id, only: [:show]
      end
      namespace :customer do
        resources :accounts,      only: [:create], path: '/'
        resources :charges,       only: [:create]
        resource  :cards_present, only: [:show]
        resources :cards,         only: [:index, :update, :destroy] do
          get :default, on: :collection
        end
      end

      namespace :additional_payments do
        resources :confirms, only: [:create]
        resources :rejects,  only: [:create]
      end

      namespace :order_items do
        resources :starts,              only: [:create]
        resource  :searchs,             only: [:create]
        resource  :completes,           only: [:create]
        resource  :pays,                only: [:create]
        resource  :cancels,             only: [:create]
      end

      mount_devise_token_auth_for 'User::Client', at: 'auth', controllers: {
        sessions:      'api/v2/auth/sessions',
        registrations: 'api/v2/auth/registrations',
        passwords:     'api/v2/auth/passwords'
      }
      resources :order_items,        only: [:index, :create, :show] do
        resources :client_feedbacks, only: [:create], as: :feedback
      end

      resources :subcategories,    only: [:index, :show] # not for API
      resources :services,         only: [:index] # not for API
      resources :categories,       only: [:index, :show] do
        resources :services,       only: [:index]
      end

      resources :stationaries,               only: [:index, :show]
      resources :gift_cards,                 only: [:create]
      namespace :gift_cards do
        resources :uses, only: [:create]
      end
      resources :offices,                    only: [:index]
      resources :posts,                      only: [:index]
      resources :images,                     only: [:create]
      resources :banners,                    only: [:index]
      resources :helps,                      only: [:create]
      resources :contacts,                   only: [:index]
      resources :conditions,                 only: [:index]
      resources :faqs,                       only: [:index]
      resources :additional_payments,        only: [:show]
      resources :timetables,                 only: [:index]
      resources :feedback_apps,              only: [:create]
      resources :partners,                   only: [:index]
      resources :referal_shares,             only: [:create]
      resources :demo_requests,              only: [:create]
      namespace :promo_codes do
        resources :check, only: [:create]
      end

      namespace :client do
        resource :device, only: [:create]
      end
    end

    namespace :v3 do
      resources :timetables,                 only: [:index]
    end

    namespace :masters do
      namespace :v1 do
        namespace :auth do
          post 'provider/facebook',    to: 'socials#facebook'
          post 'generate',             to: 'verifications#generate'

app/controllers/admin/panel/admin_users_controller.rb
module Admin
  module Panel
    class AdminUsersController < ApplicationController
      layout 'panel'

      before_action :remove_password, only: [:update]

      def index
        result = AdminUsers::Index.call(params: params)
        @admin_users = result.data
      end

      def show
        @admin_user = AdminUser.find(params[:id])
      end

      def new
        @admin_user = AdminUser.new
      end

      def create
        @admin_user = AdminUser.new permit_params

        if @admin_user.save
          redirect_to admin_panel_admin_users_path
        else
          render :new
        end
      end

      def edit
        @admin_user = AdminUser.find(params[:id])
      end

      def update
        @admin_user = AdminUser.find(params[:id])

        if @admin_user.update_attributes permit_params
          redirect_to admin_panel_admin_user_path(@admin_user)
        else
          render :edit
        end
      end

      def destroy
        @admin_user = AdminUser.find(params[:id])
        if @admin_user.destroy
          flash[:success] = 'AdminUser successfully deleted!'
        else
          flash[:error] = @admin_user.errors.full_messages.first
        end
        redirect_to admin_panel_admin_users_path
      end

      private

      def permit_params
        params.require(:admin_user).permit(:email, :role, :platform, :password, :password_confirmation, access_items: [])
      end

      def remove_password
        params[:admin_user].delete :password              if !params[:admin_user][:password].present?
        params[:admin_user].delete :password_confirmation if !params[:admin_user][:password_confirmation].present?
      end
    end
  end
end

app/controllers/admin/panel/banners_controller.rb
module Admin
  module Panel
    class BannersController < ApplicationController
      layout 'panel'

      def index
        result = Banners::Index.call(params: params)
        @banners = result.data
      end

      def show
        @banner = Banner.find(params[:id])
      end

      def new
        @banner = Banner.new
      end

      def create
        @banner = Banner.new(banner_params)

        if @banner.save
          flash[:success] = 'Banner successfully created!'
          redirect_to admin_panel_banners_path
        else
          flash[:error] = @service.errors.full_messages.first
          render :new
        end
      end

      def edit
        @banner = Banner.find(params[:id])
      end

      def update
        @banner = Banner.find(params[:id])

        if @banner.update_attributes(banner_params)
          flash[:success] = 'Banner successfully updated!'
          redirect_to admin_panel_banner_path(@banner)
        else
          flash[:error] = @banner.errors.full_messages.first
          render :edit
        end
      end

      def destroy
        @banner = Banner.find(params[:id])
        if @banner.destroy
          flash[:success] = 'Banner successfully deleted!'
        else
          flash[:error] = @banner.errors.full_messages.first
        end
        redirect_to admin_panel_banners_path
      end

      private

      def banner_params
        params.require(:banner).permit(:title, :description, :image)
      end
    end
  end
end

app/controllers/admin/panel/call_mes_controller.rb
module Admin
  module Panel
    class CallMesController < ApplicationController
      layout 'panel'

      def index
        @calls = CallMe.all.page(params[:page])
      end

      def show
        @call = CallMe.find(params[:id])
      end
    end
  end
end

app/controllers/admin/panel/categories_controller.rb
module Admin
  module Panel
    class CategoriesController < ApplicationController
      layout 'panel'

      def index
        # @categories = Category.order(:position).all
        result = Categories::Index.call(params: params)
        @categories = result.data
      end

      def show
        @category = Category.find(params[:id])
      end

      def new
        @category = Category.new
      end

      def create
        @category = Category.new(category_params)

        if @category.save
          flash[:success] = 'Category successfully created!'
          redirect_to admin_panel_categories_path
        else
          flash[:error] = @category.errors.full_messages.first
          render :new
        end
      end

      def edit
        @category = Category.find(params[:id])
      end

      def update
        @category = Category.find(params[:id])

        if @category.update_attributes(category_params)
          if params[:category][:remove_image] == '1'
            @category.remove_image!
            @category.save
          end
          flash[:success] = 'Category successfully updated!'
          redirect_to admin_panel_category_path(@category)
        else
          flash[:error] = @category.errors.full_messages.first
          render :edit
        end
      end

      def destroy
        @category = Category.find(params[:id])
        if @category.destroy
          flash[:success] = 'Category successfully deleted!'
        else
          flash[:error] = @category.errors.full_messages.first
        end
        redirect_to admin_panel_categories_path
      end

      def sortable_update
        params[:Category].each_with_index do |id, index|
          Category.where(id: id).update_all(position: index + 1)
        end
        render json: { message: 'Success' }, status: 200
      end

      private

      def category_params
        params.require(:category).permit(:id, :title, :title_ru, :parent_id, :image, :icon, :icon_web, :visible, :position, :description, :duration, :corp)
      end
    end
  end
end

app/controllers/admin/panel/cities_controller.rb
module Admin
  module Panel
    class CitiesController < ApplicationController
      layout 'panel'

      def index
        result = Cities::Index.call(params: params)
        @cities = result.data
      end

      def show
        @city = City.find(params[:id])
      end

      def new
        @city = City.new
      end

      def create
        @city = City.new(city_params)

        if @city.save
          flash[:success] = 'City successfully created!'
          redirect_to admin_panel_cities_path
        else
          flash[:error] = @city.errors.full_messages.first
          render :new
        end
      end

      def edit
        @city = City.find(params[:id])
      end

      def update
        @city = City.find(params[:id])

        if @city.update_attributes(city_params)
          flash[:success] = 'City successfully updated!'
          redirect_to admin_panel_city_path(@city)
        else
          flash[:error] = @city.errors.full_messages.first
          render :edit
        end
      end

      def destroy
        @city = City.find(params[:id])
        if @city.destroy
          flash[:success] = 'City successfully deleted!'
        else
          flash[:error] = @city.errors.full_messages.first
        end
        redirect_to admin_panel_cities_path
      end

      def city_params
        params.require(:city).permit(:name, :description, :image, :country_id)
      end
    end
  end
end

app/controllers/admin/panel/client_feedbacks_controller.rb
module Admin
  module Panel
    class ClientFeedbacksController < ApplicationController
      layout 'panel'

      def index
        result = ClientFeedbacks::Index.call(params: params)
        @client_feedbacks = result.data
      end

      def show
        @client_feedback = ClientFeedback.find(params[:id])
      end
    end
  end
end

app/controllers/admin/panel/demo_requests_controller.rb
module Admin
  module Panel
    class DemoRequestsController < ApplicationController
      layout 'panel'
      before_action :authenticate_admin_user!

      def index
        @requests = DemoRequest.all.page(params[:page])
      end

      def show
        @request = DemoRequest.find(params[:id])
      end
    end
  end
end

app/views/admin/panel/offices/index.html.erb
<div class="be-wrapper be-fixed-sidebar">
  <%= render partial: 'admin/panel/partials/header' %>

  <%= render partial: 'admin/panel/partials/sidebar' %>

  <div class="be-content">
    <div class="page-head">
      <h2 class="page-head-title">Offices</h2>
      <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb page-head-nav">
          <li class="breadcrumb-item"><a href="<%= admin_panel_path %>">Home</a></li>
          <li class="breadcrumb-item"><a href="<%= admin_panel_offices_path %>">Office</a></li>
          <li class="breadcrumb-item active">List</li>
        </ol>
      </nav>
    </div>
    <div class="main-content container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card card-table">
            <%= form_tag admin_panel_offices_path, method: :get, id: 'office_filters_form' do%>
              <div class="row table-filters-container">
                <div class="col-4 col-lg-4 table-filters pb-0 pb-xl-4 filter_blocks">
                  <div class="row">
                    <div class="col-12 col-lg-12 table-filters pb-0 pb-xl-5" style="padding-top: 0; padding-bottom: 0 !important;"><span class="table-filter-title title_filter">Title</span>
                      <div class="filter-container">
                        <label class="control-label">Find by title:</label>
                        <div class="row">
                          <div class="col-6">
                            <%= select_tag :title_filter, options_for_select(get_filter_options, params[:title_filter]), { class: 'select2 select2-hidden-accessible title_filter' } %>
                          </div>
                          <div class="col-6">
                            <%= text_field_tag :title, params[:title], class: 'form-control form-control-sm title' %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-4 col-lg-4 table-filters pb-0 pb-xl-4 filter_blocks">
                  <div class="row">
                    <div class="col-12 col-lg-12 table-filters pb-0 pb-xl-5" style="padding-top: 0; padding-bottom: 0 !important;"><span class="table-filter-title title_filter">Client</span>
                      <div class="filter-container">
                        <label class="control-label">Find by client:</label>
                        <div class="row">
                          <div class="col-12">
                            <%= select_tag :client_id, options_for_select(User::Client.all.map{ |client| [client.name, client.id] }, params[:client_id]), { class: 'select2 select2-hidden-accessible client_id', id: 'client_id' } %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12 col-lg-12 table-filters pb-0 pb-xl-5">
                    <div class="filter-container">
                      <div class="row">
                        <div class="col-7" style="padding-right: 0 !important;">
                        </div>
                        <div class="col-4" style="padding-right: 0 !important;">
                          <div class="custom-controls-stacked">
                            <a href="<%= new_admin_panel_office_path %>" class="btn btn-space btn-secondary">New office</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-4 col-lg-4 table-filters pb-0 pb-xl-4 filter_blocks">
                  <div class="row">
                    <div class="col-12 col-lg-12 table-filters pb-0 pb-xl-5" style="padding-top: 0; padding-bottom: 0 !important;"><span class="table-filter-title title_filter">Count vehicles</span>
                      <div class="filter-container">
                        <label class="control-label">Count vehicles:</label>
                        <div class="row">
                          <div class="col-6">
                            <%= select_tag :count_vehicle_filters, options_for_select(get_number_filter_options, params[:count_vehicle_filters]), { class: 'select2 select2-hidden-accessible count_vehicle_filter' } %>
                          </div>
                          <div class="col-6">
                            <%= number_field_tag :count_vehicles, params[:count_vehicles], class: 'form-control form-control-sm count_vehicles' %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="col-10 col-lg-10 table-filters pb-0 pb-xl-4 filter_buttons">
                  <div class="row">
                    <div class="col-12 col-lg-12 table-filters filter_blocks">
                      <div class="filter-container">
                        <%= submit_tag('Filter', type: 'submit', class: 'btn btn-space btn-primary') %>
                        <%= submit_tag('Reset', type: 'cancel', class: 'btn btn-space btn-secondary reset_office_filters') %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="card-body">
              <div class="noSwipe">
                <table class="table table-striped table-hover be-table-responsive" id="table1">
                  <thead>
                  <tr>
                    <th>
                      <label class="custom-control custom-control-sm custom-checkbox">
                        <input class="custom-control-input" type="checkbox"><span class="custom-control-label"></span>
                      </label>
                    </th>
                    <th>id</th>
                    <th>Title</th>
                    <th>Client</th>
                    <th>Count vehicles</th>
                    <th>Address</th>
                  </tr>
                  </thead>
                  <tbody class="sortable">
                  <% @offices.each do |office| %>
                    <tr class="success done">
                      <td>
                        <label class="custom-control custom-control-sm custom-checkbox">
                          <input class="custom-control-input" type="checkbox"><span class="custom-control-label"></span>
                        </label>
                      </td>
                      <td class="cell-detail"><span><a href="<%= admin_panel_office_path(office.id) %>"><%= office.id %></a></span></td>
                      <td class="cell-detail"><span><%= office.title %></span></td>
                      <td class="cell-detail"><span><%= link_to office.client.name, admin_panel_client_path(office.client) if office.client.present? %></span></td>
                      <td class="cell-detail"><span><%= office.count_vehicles %></span></td>
                      <td class="cell-detail"><span><%= office.address %></span></td>
                      <td class="text-right">
                        <div class="btn-group btn-hspace">
                          <button class="btn btn-secondary dropdown-toggle" type="button" data-toggle="dropdown">Actions
                            <span class="icon-dropdown mdi mdi-chevron-down"></span></button>
                          <div class="dropdown-menu" role="menu">
                            <a class="dropdown-item" href="<%= admin_panel_office_path(office) %>">Show</a>
                            <a class="dropdown-item" href="<%= edit_admin_panel_office_path(office) %>">Edit</a>
                            <a class="dropdown-item" href="<%= admin_panel_office_path(office) %>" data-method="delete" data-confirm="Are you sure?">Delete</a>
                          </div>
                        </div>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render partial: 'admin/panel/partials/navigation_bar' %>
</div>
<%= content_for :javascript do %>
  <script type="text/javascript">
    App.init();
    App.formElements();
    stop_preloader();

    $('.reset_office_filters').on('click', function(){
      $('#office_filters_form')[0].reset();
      window.location.href = '/admin/panel/offices'
    });

    <% unless params[:client_id].present? %>
      $('#client_id').val('').trigger('change');
    <% end %>

    <%= render partial: 'admin/panel/partials/flash_msg' %>
  </script>
<% end %>

app/views/admin/panel/offices/show.html.erb
<%= render 'admin/shared/map' %>
<div class="be-wrapper be-fixed-sidebar">
  <%= render partial: 'admin/panel/partials/header' %>

  <%= render partial: 'admin/panel/partials/sidebar' %>

  <div class="be-content">
    <div class="page-head">
      <h2 class="page-head-title">Offices</h2>
      <nav aria-label="breadcrumb" role="navigation">
        <ol class="breadcrumb page-head-nav">
          <li class="breadcrumb-item"><a href="<%= admin_panel_path %>">Home</a></li>
          <li class="breadcrumb-item"><a href="<%= admin_panel_order_items_path %>">Offices</a></li>
          <li class="breadcrumb-item active">Show</li>
        </ol>
      </nav>
    </div>
    <div class="main-content container-fluid">
      <div class="user-profile">
        <div class="row">
          <div class="col-lg-12">
            <div class="user-info-list card">
              <div class="card-header card-header-divider">Office
                <span class="card-subtitle"> Information
                  <div class="icon-container">
                    <a href="<%= edit_admin_panel_office_path(@office)%>">
                      <div class="icon"><span class="mdi mdi-edit"></span></div>
                      <span class="icon-class">Edit</span>
                    </a>
                  </div>
                </span>
              </div>
              <div class="card-body">
                <table class="no-border no-strip skills">
                  <tbody class="no-border-x no-border-y">
                  <tr>
                    <td class="icon"><span class="mdi mdi-account"></span></td>
                    <td class="item">Title<span class="icon s7-portfolio"></span></td>
                    <td><%= @office.title %></td>
                  </tr>
                  <tr>
                    <td class="icon"><span class="mdi mdi-account"></span></td>
                    <td class="item">Client<span class="icon s7-portfolio"></span></td>
                    <td><%= link_to @office.client.name, admin_panel_client_path(@office.client) if @office.client.present? %></td>
                  </tr>
                  <tr>
                    <td class="icon"><span class="mdi mdi-account"></span></td>
                    <td class="item">Count vehicles<span class="icon s7-portfolio"></span></td>
                    <td><%= @office.count_vehicles %></td>
                  </tr>
                  <tr>
                    <td class="icon"><span class="mdi mdi-account"></span></td>
                    <td class="item">Address<span class="icon s7-portfolio"></span></td>
                    <td><%= @office.address %></td>
                  </tr>
                  </tbody>
                </table>
              </div>

            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="user-info-list card">
              <div class="card-header card-header-divider">Office's location<span class="card-subtitle"></span></div>
              <div class="card-body">
                <div id="map_client" class="content" style="height: 350px;"></div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  <%= render partial: 'admin/panel/partials/navigation_bar' %>
</div>
<%= content_for :javascript do %>
  <script type="text/javascript">
    App.init();
    App.formElements();
    // App.tableFilters();
    stop_preloader();

    <%= render partial: 'admin/panel/partials/flash_msg' %>

    var officesLatLng = initCoords();
    initMapClient();
    function initMapClient() {
      // Create a map object and specify the DOM element for display.
      var map = new google.maps.Map(document.getElementById('map_client'), {
        center: officesLatLng,
        scrollwheel: true,
        zoom: 13,
        mapTypeId:google.maps.MapTypeId.ROADMAP,
        disableDefaultUI: true,
        zoomControl: true,
        scaleControl: true
      });

      if(officesLatLng){
        var marker = new google.maps.Marker({
          position: officesLatLng,
          map: map
        });
      }

      if(gon.master){
        infoWindowText = gon.master.name ? gon.master.name : gon.master.email;
        var infoWindow = new google.maps.InfoWindow({
          content: infoWindowText
        });

        google.maps.event.addListener(marker, 'click', function () {
          infoWindow.open(map, marker);
        });
      }

    }

    function initCoords() {
      if(gon.office){
        lat = gon.office.lat ? Number.parseFloat(gon.office.lat) : 53.3374107;
        lon = gon.office.lon ? Number.parseFloat(gon.office.lon) : -6.3122344;
        return { lat: lat, lng: lon };
      }
    }
  </script>
<% end %>